---
parent: Api_tactics_group-by-values
name: ApiTacticsGroupByValuesPostIncrementalIds
description: '**PreAuthorize:** hasPermission(authentication, ''bulk_process_read'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/tactics/group-by-values
endpoint: /api/tactics/group-by-values
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "groupBy1" : "{{@Random}}",
      "groupBy2" : "{{@Random}}",
      "selection" : "{{@Random}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@Response.data.id != @NULL AND @Response.data.id != @Number'
- '@StatusCode == 200'
cleanup: []
severity: Medium
category: Incremental_Ids
tags:
- V1
- OWASP-API3
- CWE - 99
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
