---
parent: Api_dynamicbrowser-configuration_delete
name: ApiDynamicbrowserConfigurationDeletePostAllowedRbac
description: "**PreAuthorize:** hasPermission(authentication, 'parameters_write')<br\
  \ /><br />**Notes:** First find a valid profileId from UserSelectConfig by:\n select\
  \ top 1 profileId  from UserSelectConfig "
authors:
- apisec Bot
type: SUITE
init: []
path: /api/dynamicbrowser-configuration/delete
endpoint: /api/dynamicbrowser-configuration/delete
method: POST
auth: ROLE_parameters_write
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "profilesToRemove" : [ {
        "profile" : "{{@Random}}",
        "variantId" : "{{@Random}}"
      } ]
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode != 401 AND @StatusCode != 403'
cleanup: []
severity: High
category: RBAC
tags:
- V1
- OWASP-API5
- OWASP - OTG-IDENT-001
- OWASP API Security Top 10
- Broken Function Level Authorization
- Endpoint_Access_Control
- '[2020 CWE TOP 22 ] CWE - 269'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
