---
parent: Api_warehouse-config_profile
name: ApiWarehouseConfigProfilePostAuthInvalidEmpty
description: '**PreAuthorize:** hasPermission(authentication, ''bulk_process_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/warehouse-config/profile
endpoint: /api/warehouse-config/profile
method: POST
auth: Invalid_Auth_Empty
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "autoUpdate" : true,
          "excludeActive" : true,
          "excludeUser" : true,
          "forecastStartWeek" : 0,
          "lastSalesMonth" : 0,
          "mainWarehouseCode" : "CDC",
          "numberOfSatellites" : "12",
          "satelliteUpdate" : true,
          "satelliteUpdateNew" : false,
          "satellites" : [ {
            "mainWarehouseCode" : "CDC",
            "satelliteWarehouse" : "SZD",
            "satelliteWarehouseName" : "Shop Zaandam"
          } ],
          "seasonalProfile" : true,
          "warehouseName" : "Central warehouse Amsterdam"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode == 401 OR @StatusCode == 403'
cleanup: []
severity: Critical
category: InvalidAuthEmpty
tags:
- V1
- OWASP-API2
- '[PCI DSS 3.0] 6.5.8'
- '[PCI DSS 3.0] 6.5.10'
- OTG-AUTHN-004
- OWASP API Security Top 10
- Broken Authentication
- Non-Intrusive
- '[2020 CWE TOP 24] CWE - 306'
- '[MITRE ATT&CK] T1595.002'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: true
  postExecutionDelay: 0
autoGenerated: true
