---
parent: Api_warehouse-config_profile
name: ApiWarehouseConfigProfilePostDisallowedRbac
description: '**PreAuthorize:** hasPermission(authentication, ''bulk_process_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/warehouse-config/profile
endpoint: /api/warehouse-config/profile
method: POST
auth: ROLE_system_write,ROLE_extract_read,ROLE_promotions_write,ROLE_order_read,ROLE_promotions_read,ROLE_users_write,ROLE_parameters_write,ROLE_bulk_process_write,ROLE_selection_write,ROLE_selection_read,ROLE_users_read,ROLE_comment,ROLE_scheduler_write,ROLE_scheduler_read,ROLE_article_write,ROLE_article_read,ROLE_user_write,ROLE_extract_write,ROLE_order_write,ROLE_system_read
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "autoUpdate" : true,
          "excludeActive" : true,
          "excludeUser" : true,
          "forecastStartWeek" : 0,
          "lastSalesMonth" : 0,
          "mainWarehouseCode" : "CDC",
          "numberOfSatellites" : "12",
          "satelliteUpdate" : true,
          "satelliteUpdateNew" : false,
          "satellites" : [ {
            "mainWarehouseCode" : "CDC",
            "satelliteWarehouse" : "SZD",
            "satelliteWarehouseName" : "Shop Zaandam"
          } ],
          "seasonalProfile" : true,
          "warehouseName" : "Central warehouse Amsterdam"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode == 401 OR @StatusCode == 403'
cleanup: []
severity: High
category: RBAC
tags:
- V1
- OWASP-API5
- OWASP - OTG-IDENT-001
- OWASP API Security Top 10
- Broken Function Level Authorization
- Endpoint_Access_Control
- '[2020 CWE TOP 22 ] CWE - 269'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
