---
parent: Api_demand-transactions-outlier_settings
name: ApiDemandTransactionsOutlierSettingsPutAnonymousInvalid
description: '**PreAuthorize:** hasPermission(authentication, ''parameters_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/demand-transactions-outlier/settings
endpoint: /api/demand-transactions-outlier/settings
method: PUT
auth: Anonymous
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
          "accuracyThreshold" : 80.0,
          "automaticExclusion" : 0,
          "confidenceThreshold" : 80.0,
          "outlierThreshold" : 0.0
        }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode == 401 OR @StatusCode == 403'
cleanup: []
severity: Critical
category: Unsecured
tags:
- V1
- OWASP-API2
- OWASP-API7
- OWASP - OTG-AUTHN-002
- OWASP API Security Top 10
- Broken Authentication
- Security Misconfiguration
- Non-Intrusive
- '[2020 CWE TOP 24] CWE - 306'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
