---
parent: Api_demand-transactions-outlier_settings
name: ApiDemandTransactionsOutlierSettingsPutAllowedRbac
description: '**PreAuthorize:** hasPermission(authentication, ''parameters_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/demand-transactions-outlier/settings
endpoint: /api/demand-transactions-outlier/settings
method: PUT
auth: ROLE_parameters_write
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
          "accuracyThreshold" : 80.0,
          "automaticExclusion" : 0,
          "confidenceThreshold" : 80.0,
          "outlierThreshold" : 0.0
        }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode != 401 AND @StatusCode != 403'
cleanup: []
severity: High
category: RBAC
tags:
- V1
- OWASP-API5
- OWASP - OTG-IDENT-001
- OWASP API Security Top 10
- Broken Function Level Authorization
- Endpoint_Access_Control
- '[2020 CWE TOP 22 ] CWE - 269'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
