---
parent: Api_dynamicbrowser-configuration
name: ApiDynamicbrowserConfigurationPutAuthInvalidSql
description: '**PreAuthorize:** hasPermission(authentication, ''parameters_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/dynamicbrowser-configuration
endpoint: /api/dynamicbrowser-configuration?profileId={{@Var.profileId}}&variantId=ARTICLECONFIRMEDORDERDETAILS
method: PUT
auth: Invalid_Auth_SQL
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "availableColumns" : [ {
        "aggregate" : "{{@Random}}",
        "autoF8" : "{{@RandomInteger}}",
        "columnSelect" : "{{@RandomInteger}}",
        "columnSql" : "{{@Random}}",
        "columnType" : "{{@RandomInteger}}",
        "decimalPlaces" : "{{@RandomInteger}}",
        "desc3" : "{{@RandomInteger}}",
        "editable" : false,
        "field" : "{{@Random}}",
        "hidden" : false,
        "hybridId" : "{{@Random}}",
        "isEditablePermittedOnField" : false,
        "isSortingPermittedOnField" : false,
        "justification" : "{{@RandomInteger}}",
        "orderTypeNumber" : "{{@Random}}",
        "screenSize" : "{{@Random}}",
        "showRowLock" : "{{@RandomInteger}}",
        "showRowNum" : "{{@RandomInteger}}",
        "sortDirection" : "{{@RandomInteger}}",
        "sortPriority" : "{{@RandomInteger}}",
        "text" : "{{@Random}}",
        "textFCode" : "{{@Random}}",
        "tooltip" : "{{@Random}}",
        "type" : "{{@Random}}",
        "usePurchaseContract" : "{{@RandomInteger}}",
        "width" : "{{@RandomInteger}}"
      } ],
      "columns" : [ {
        "aggregate" : "{{@Random}}",
        "autoF8" : "{{@RandomInteger}}",
        "columnSelect" : "{{@RandomInteger}}",
        "columnSql" : "{{@Random}}",
        "columnType" : "{{@RandomInteger}}",
        "decimalPlaces" : "{{@RandomInteger}}",
        "desc3" : "{{@RandomInteger}}",
        "editable" : false,
        "field" : "{{@Random}}",
        "hidden" : false,
        "hybridId" : "{{@Random}}",
        "isEditablePermittedOnField" : false,
        "isSortingPermittedOnField" : false,
        "justification" : "{{@RandomInteger}}",
        "orderTypeNumber" : "{{@Random}}",
        "screenSize" : "{{@Random}}",
        "showRowLock" : "{{@RandomInteger}}",
        "showRowNum" : "{{@RandomInteger}}",
        "sortDirection" : "{{@RandomInteger}}",
        "sortPriority" : "{{@RandomInteger}}",
        "text" : "{{@Random}}",
        "textFCode" : "{{@Random}}",
        "tooltip" : "{{@Random}}",
        "type" : "{{@Random}}",
        "usePurchaseContract" : "{{@RandomInteger}}",
        "width" : "{{@RandomInteger}}"
      } ],
      "profile" : "{{@Random}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseTime < 7000'
cleanup: []
severity: Critical
category: InvalidAuthSQL
tags:
- V1
- OWASP-API2
- '[PCI DSS 3.0] 6.5.1'
- OTG-AUTHN-004
- OWASP API Security Top 10
- Broken Authentication
- Non-Intrusive
- Injection
- '[2020 CWE TOP 14] CWE - 287'
- '[MITRE ATT&CK] T1595.002'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@Apisec/Common/auth_invalid_sql'
  repeatDelay: 0
  unmaskToken: true
  postExecutionDelay: 0
autoGenerated: true
