---
parent: Api_dynamicbrowser-configuration
name: ApiDynamicbrowserConfigurationPostBodyParamXssInjection
description: '**PreAuthorize:** hasPermission(authentication, ''parameters_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/dynamicbrowser-configuration
endpoint: /api/dynamicbrowser-configuration?variantId=ARTICLECONFIRMEDORDERDETAILS
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "availableColumns" : [ {
        "aggregate" : "{{@Random}}",
        "autoF8" : "{{@RandomInteger}}",
        "columnSelect" : "{{@RandomInteger}}",
        "columnSql" : "{{@Random}}",
        "columnType" : "{{@RandomInteger}}",
        "decimalPlaces" : "{{@RandomInteger}}",
        "desc3" : "{{@RandomInteger}}",
        "editable" : false,
        "field" : "{{@Random}}",
        "hidden" : false,
        "hybridId" : "{{@Random}}",
        "isEditablePermittedOnField" : false,
        "isSortingPermittedOnField" : false,
        "justification" : "{{@RandomInteger}}",
        "orderTypeNumber" : "{{@Random}}",
        "screenSize" : "{{@Random}}",
        "showRowLock" : "{{@RandomInteger}}",
        "showRowNum" : "{{@RandomInteger}}",
        "sortDirection" : "{{@RandomInteger}}",
        "sortPriority" : "{{@RandomInteger}}",
        "text" : "{{@Random}}",
        "textFCode" : "{{@Random}}",
        "tooltip" : "{{@Random}}",
        "type" : "{{@Random}}",
        "usePurchaseContract" : "{{@RandomInteger}}",
        "width" : "{{@RandomInteger}}"
      } ],
      "columns" : [ {
        "aggregate" : "{{@Random}}",
        "autoF8" : "{{@RandomInteger}}",
        "columnSelect" : "{{@RandomInteger}}",
        "columnSql" : "{{@Random}}",
        "columnType" : "{{@RandomInteger}}",
        "decimalPlaces" : "{{@RandomInteger}}",
        "desc3" : "{{@RandomInteger}}",
        "editable" : false,
        "field" : "{{@Random}}",
        "hidden" : false,
        "hybridId" : "{{@Random}}",
        "isEditablePermittedOnField" : false,
        "isSortingPermittedOnField" : false,
        "justification" : "{{@RandomInteger}}",
        "orderTypeNumber" : "{{@Random}}",
        "screenSize" : "{{@Random}}",
        "showRowLock" : "{{@RandomInteger}}",
        "showRowNum" : "{{@RandomInteger}}",
        "sortDirection" : "{{@RandomInteger}}",
        "sortPriority" : "{{@RandomInteger}}",
        "text" : "{{@Random}}",
        "textFCode" : "{{@Random}}",
        "tooltip" : "{{@Random}}",
        "type" : "{{@Random}}",
        "usePurchaseContract" : "{{@RandomInteger}}",
        "width" : "{{@RandomInteger}}"
      } ],
      "profile" : "{{@Injection}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode != 200 OR @Response.success == false OR @Response.success == true'
cleanup: []
severity: Medium
category: XSS_Injection
tags:
- V1
- OWASP-API8
- '[PCI DSS 3.0] 6.5.7'
- '[PCI DSS 3.2] 6.5.7'
- '[PCI DSS 3.2.1] 6.5.7'
- OWASP - OTG-INPVAL-001
- OWASP - OTG-INPVAL-002
- OWASP API Security Top 10
- Excessive Data Exposure
- Security Misconfiguration
- INPUT VALIDATION
- NON-INTRUSIVE
- '[2020 CWE TOP 1 ] CWE - 79'
- '[MITRE ATT&CK] T1190'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@APIsec/Common/XSS_Injection_Strings'
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
