---
parent: Api_system_exchange-settings
name: ApiSystemExchangeSettingsPostBodyParamSqlInjectionTimebound
description: '**PreAuthorize:** hasPermission(authentication, ''system_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/system/exchange-settings
endpoint: /api/system/exchange-settings
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "lastAdditional":"0","lastAutoDetect":"0","lastCollection":"0","lastConfirmedForecast":"0","lastExportParh":"{{@Injection}}","lastExportType":"0","lastFileType":"0","lastFormat":"0","lastGroup":"0","lastImportPath":"string","lastImportType":"0","lastInsurance":"0","lastRunCode":"0"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseTime < 7000'
cleanup: []
severity: Critical
category: sql_injection_timebound
tags:
- V1
- OWASP-API8
- '[PCI DSS 3.0] 6.5.1'
- '[PCI DSS 3.2.1] 6.5.1'
- OWASP - OTG-INPVAL-005
- OWASP API Security Top 10
- Injection
- Intrusive
- '[2020 CWE TOP 6] CWE - 89'
- '[MITRE ATT&CK] T1190'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: ""
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
