---
parent: Api_system_exchange-settings
name: ApiSystemExchangeSettingsPostAuthInvalidSql
description: '**PreAuthorize:** hasPermission(authentication, ''system_write'')'
authors:
- apisec Bot
type: SUITE
init: []
path: /api/system/exchange-settings
endpoint: /api/system/exchange-settings
method: POST
auth: Invalid_Auth_SQL
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "lastAdditional" : "{{@RandomInteger}}",
      "lastAutoDetect" : "{{@RandomInteger}}",
      "lastCollection" : "{{@RandomInteger}}",
      "lastConfirmedForecast" : "{{@RandomInteger}}",
      "lastExportParh" : "{{@Random}}",
      "lastExportType" : "{{@RandomInteger}}",
      "lastFileType" : "{{@RandomInteger}}",
      "lastFormat" : "{{@RandomInteger}}",
      "lastGroup" : "{{@RandomInteger}}",
      "lastImportPath" : "{{@Random}}",
      "lastImportType" : "{{@RandomInteger}}",
      "lastInsurance" : "{{@RandomInteger}}",
      "lastRunCode" : "{{@RandomInteger}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseTime < 7000'
cleanup: []
severity: Critical
category: InvalidAuthSQL
tags:
- V1
- OWASP-API2
- '[PCI DSS 3.0] 6.5.1'
- OTG-AUTHN-004
- OWASP API Security Top 10
- Broken Authentication
- Non-Intrusive
- Injection
- '[2020 CWE TOP 14] CWE - 287'
- '[MITRE ATT&CK] T1595.002'
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@Apisec/Common/auth_invalid_sql'
  repeatDelay: 0
  unmaskToken: true
  postExecutionDelay: 0
autoGenerated: true
